FROM php:8.2-fpm

RUN docker-php-ext-install pdo pdo_mysql
RUN pecl install xdebug && docker-php-ext-enable xdebug

WORKDIR /var/www/html
COPY docker/php/xdebug.ini /usr/local/etc/php/conf.d/99-xdebug.ini

EXPOSE 9000